default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  socket: /opt/boxen/data/socket

development:
  <<: *default
  database: xperior

test:
  <<: *default
  database: xperior_test
